language: go

go:
  - 1.0
  - 1.1
  - tip

before_script:
  - mkdir -p $TRAVIS_BUILD_DIR/src
  - mkdir -p $TRAVIS_BUILD_DIR/src/chip
  = mv $TRAVIS_BUILD_DIR/* $TRAVIS_BUILD_DIR/src/chip
  - export GOPATH=$GOPATH:$HOME/gopath/src/github.com/jackspirou/src
